export const policyData = `
<h1 dir="ltr" style="line-height: 1.2; margin-top: 0pt; margin-bottom: 8pt; text-align: center;"><strong><span font-size:="" font-weight:="" new="" style="color: rgb(0, 0, 0); font-family: " text-align:="" times="" white-space:="">Điều khoản sử dụng Chamm</span></strong></h1>
<p dir="ltr" style="line-height:1.2;margin-top:0pt;margin-bottom:8pt;text-align: justify;"><span style="font-size:14px;"><span id="docs-internal-guid-cfcf0f1b-7fff-0981-4e13-2182d94bfe0a"><span color:="" font-variant-east-asian:="" font-variant-numeric:="" new="" times="" vertical-align:="" white-space:="">Các điều khoản này chi phối việc bạn sử dụng trang web mentori.vn và các sản phẩm, tính năng và dịch vụ mà Mentori cung cấp, trừ khi chúng tôi nêu rõ rằng các điều khoản riêng biệt đó được áp dụng.</span></span></span></p>
<h2 dir="ltr" style="list-style-type: upper-roman; font-size: 12pt; margin-top: 12pt; margin-bottom: 0pt;"><span style="font-size:20px;"><span id="docs-internal-guid-cfcf0f1b-7fff-0981-4e13-2182d94bfe0a"><span style="background-color: transparent; font-weight: 700; font-variant-numeric: normal; font-variant-east-asian: normal; vertical-align: baseline; white-space: pre-wrap;">I. Dịch vụ Chamm, Phần mềm Chamm</span></span></span></h2>
<ul dir="ltr">
<li style="list-style-type: disc; font-size: 12pt; line-height: 1.2; margin-top: 0pt; margin-bottom: 0pt; margin-left: 30pt; text-align: justify;">
<p><span style="font-size:14px;"><span id="docs-internal-guid-cfcf0f1b-7fff-0981-4e13-2182d94bfe0a"><span style="background-color: transparent; font-weight: 700; font-variant-numeric: normal; font-variant-east-asian: normal; vertical-align: baseline; white-space: pre-wrap;">Sử dụng Dịch vụ Chamm trên Sản phẩm:</span><span style="background-color: transparent; font-variant-numeric: normal; font-variant-east-asian: normal; vertical-align: baseline; white-space: pre-wrap;">Để sử dụng một số Dịch vụ Chamm trên Sản phẩm, bạn phải có tài khoản Chamm.com của riêng mình, đăng nhập vào tài khoản của bạn trên Sản phẩm và có phương thức thanh toán hợp lệ được liên kết với tài khoản của bạn.</span></span></span></p>
</li>
<li style="list-style-type: disc; font-size: 12pt; line-height: 1.2; margin-top: 0pt; margin-bottom: 10pt; margin-left: 30pt; text-align: justify;">
<p><span style="font-size:14px;"><span><span style="background-color: transparent; font-variant-numeric: normal; font-variant-east-asian: normal; vertical-align: baseline; white-space: pre-wrap;"><span style="font-size:14px;"><span id="docs-internal-guid-cfcf0f1b-7fff-0981-4e13-2182d94bfe0a"><span style="background-color: transparent; font-weight: 700; font-variant-numeric: normal; font-variant-east-asian: normal; vertical-align: baseline; white-space: pre-wrap;">Sử dụng phần mềm Chamm:</span><span style="background-color: transparent; font-variant-numeric: normal; font-variant-east-asian: normal; vertical-align: baseline; white-space: pre-wrap;">Trừ khi được cung cấp trong phần này, bạn chỉ có thể sử dụng Phần mềm Chamm trên Sản phẩm của mình. Để biết các điều khoản bổ sung áp dụng cho Phần mềm Chamm, hãy xem Điều khoản bổ sung của Phần mềm Chamm có trong Điều kiện sử dụng của Chamm.com và các điều khoản có trong phần Pháp lý của menu Cài đặt của Dịch vụ Chamm trên Sản phẩm của bạn hoặc Điều khiển từ xa Chamm Fire TV Ứng dụng. Phần mềm Chamm được cấp phép theo giấy phép nguồn mở chỉ chịu sự điều chỉnh của các điều khoản của giấy phép nguồn mở đó.</span></span></span></span></span></span></p>
</li>
</ul>
<h2 dir="ltr" style="list-style-type: disc; font-size: 12pt; line-height: 1.2; margin-top: 0pt; margin-bottom: 8pt;"><span style="font-size:20px;"><span style="background-color: transparent; font-variant-numeric: normal; font-variant-east-asian: normal; vertical-align: baseline; white-space: pre-wrap;"><span id="docs-internal-guid-cfcf0f1b-7fff-0981-4e13-2182d94bfe0a"><span style="font-weight: 700; font-variant-numeric: normal; font-variant-east-asian: normal; vertical-align: baseline; white-space: pre-wrap;">II. Kết nối và sẵn có</span></span></span></span></h2>
<p dir="ltr" style="line-height: 1.2; margin-top: 0pt; margin-bottom: 8pt;"><strong><span style="font-size:14px;"><span style="color: rgb(0, 0, 0); background-color: transparent; font-variant-numeric: normal; font-variant-east-asian: normal; vertical-align: baseline; white-space: pre-wrap;">1. Kết nối mạng Internet::</span></span></strong></p>
<p dir="ltr" style="line-height: 1.2; margin-top: 0pt; margin-bottom: 8pt;"><span style="font-size:14px;"><span font-size:="" new="" style="background-color: transparent; color: rgb(0, 0, 0); font-family: " times="" white-space:="">Dịch vụ Chamm có thể yêu cầu kết nối Internet từ nhà cung cấp bên thứ ba để sử dụng một số tính năng. Trong những trường hợp như vậy, kết nối Internet của bạn phải tuân theo các khoản phí, hạn chế, điều khoản và giới hạn do nhà cung cấp của bạn áp đặt.</span><span id="docs-internal-guid-cfcf0f1b-7fff-0981-4e13-2182d94bfe0a"><span style="color: rgb(0, 0, 0); background-color: transparent; font-weight: 700; font-variant-numeric: normal; font-variant-east-asian: normal; vertical-align: baseline; white-space: pre-wrap;"> </span></span></span></p>
<p dir="ltr" style="line-height: 1.2; margin-top: 0pt; margin-bottom: 8pt;"><span style="font-size:14px;"><span><span style="color: rgb(0, 0, 0); background-color: transparent; font-weight: 700; font-variant-numeric: normal; font-variant-east-asian: normal; vertical-align: baseline; white-space: pre-wrap;">2. Khả dụng:</span></span></span></p>
<p dir="ltr" style="line-height:1.2;margin-top:0pt;margin-bottom:8pt;"><span style="font-size:14px;"><span id="docs-internal-guid-cfcf0f1b-7fff-0981-4e13-2182d94bfe0a"><span background-color:="" color:="" font-variant-east-asian:="" font-variant-numeric:="" new="" times="" vertical-align:="" white-space:="">Một số Dịch vụ của Chamm có thể không khả dụng, thay đổi (ví dụ: theo sản phẩm hoặc khu vực địa lý), được cung cấp trong thời gian giới hạn hoặc yêu cầu đăng ký riêng.. </span></span></span></p>
<p dir="ltr" style="list-style-type: decimal; font-size: 12pt; margin-top: 2pt; margin-bottom: 0pt;"><span style="font-size:14px;"><span><span background-color:="" color:="" font-variant-east-asian:="" font-variant-numeric:="" new="" times="" vertical-align:="" white-space:=""> </span></span></span></p>
<h2 dir="ltr" style="list-style-type: upper-roman; font-size: 12pt; margin-top: 12pt; margin-bottom: 0pt;"><span style="font-size:20px;"><strong><span id="docs-internal-guid-cfcf0f1b-7fff-0981-4e13-2182d94bfe0a"><span style="background-color: transparent; font-weight: 700; font-variant-numeric: normal; font-variant-east-asian: normal; vertical-align: baseline; white-space: pre-wrap;">III. Tổng quan</span></span></strong></span></h2>
<p dir="ltr" style="list-style-type: upper-roman; font-size: 12pt; margin-top: 2pt; margin-bottom: 4pt;"><span style="font-size:14px;"><span><span style="color: rgb(0, 0, 0); background-color: transparent; font-weight: 700; font-variant-numeric: normal; font-variant-east-asian: normal; vertical-align: baseline; white-space: pre-wrap;">1. Thông tin đã nhận</span></span></span></p>
<p dir="ltr" style="line-height: 1.2; margin-top: 0pt; margin-bottom: 8pt;"><span style="font-size:14px;"><span id="docs-internal-guid-cfcf0f1b-7fff-0981-4e13-2182d94bfe0a"><span background-color:="" color:="" font-variant-east-asian:="" font-variant-numeric:="" new="" times="" vertical-align:="" white-space:=""> Phần mềm Chamm có thể cung cấp cho chúng tôi thông tin về Sản phẩm của bạn, việc sử dụng Sản phẩm và việc sử dụng Nội dung Kỹ thuật số, nội dung khác và Dịch vụ Chamm (chẳng hạn như truy vấn tìm kiếm, ứng dụng đã cài đặt, dữ liệu xem và sử dụng, bộ nhớ khả dụng, tệp nhật ký, chẩn đoán mạng, thông tin thoại và kết nối). Nhà sản xuất Sản phẩm của bạn cũng có thể cung cấp cho chúng tôi thông tin tương tự. Thông tin cung cấp cho Chamm có thể được xử lý trên đám mây để cải thiện trải nghiệm của bạn và các dịch vụ của chúng tôi, đồng thời có thể được lưu trữ trên các máy chủ bên ngoài quốc gia nơi bạn sinh sống. Chúng tôi sẽ xử lý bất kỳ thông tin nào chúng tôi nhận được theo Thông báo về quyền riêng tư của Chamm.com. Vui lòng truy cập menu Cài đặt trên Sản phẩm của bạn nếu bạn muốn từ chối cung cấp một số thông tin nhất định.</span></span></span></p>
<p dir="ltr" style="line-height: 1.2; margin-top: 0pt; margin-bottom: 8pt;"><strong><span style="font-size:14px;"><span><span style="background-color: transparent; font-variant-numeric: normal; font-variant-east-asian: normal; vertical-align: baseline;">2.&nbsp;</span><span style="color: rgb(0, 0, 0); background-color: transparent; font-weight: 700; font-variant-numeric: normal; font-variant-east-asian: normal; vertical-align: baseline; white-space: pre-wrap;">Thông tin được cung cấp cho người khác</span></span></span></strong></p>
<p dir="ltr" style="line-height: 1.2; margin-top: 0pt; margin-bottom: 8pt;"><span style="font-size:14px;"><span id="docs-internal-guid-cfcf0f1b-7fff-0981-4e13-2182d94bfe0a"><span background-color:="" color:="" font-variant-east-asian:="" font-variant-numeric:="" new="" times="" vertical-align:="" white-space:="">Bạn chịu trách nhiệm về bất kỳ thông tin nào bạn cung cấp cho người khác, kể cả các nhà cung cấp Nội dung Kỹ thuật số bên thứ ba. Việc sử dụng thông tin bạn cung cấp cho các bên thứ ba này sẽ phải tuân theo mọi thông báo về quyền riêng tư hoặc các điều khoản khác mà họ có thể cung cấp cho bạn.</span></span></span></p>
<p dir="ltr" style="line-height: 1.2; margin-top: 0pt; margin-bottom: 8pt;"><span style="font-size:14px;"><span><span style="color: rgb(0, 0, 0); background-color: transparent; font-weight: 700; font-variant-numeric: normal; font-variant-east-asian: normal; vertical-align: baseline; white-space: pre-wrap;">3. Thay đổi Dịch vụ Chamm; sửa đổi</span></span></span></p>
<p dir="ltr" style="line-height: 1.2; margin-top: 0pt; margin-bottom: 8pt;"><span style="font-size:14px;"><span id="docs-internal-guid-cfcf0f1b-7fff-0981-4e13-2182d94bfe0a"><span background-color:="" color:="" font-variant-east-asian:="" font-variant-numeric:="" new="" times="" vertical-align:="" white-space:=""> Chúng tôi có thể thay đổi, đình chỉ hoặc ngừng cung cấp Dịch vụ Chamm hoặc bất kỳ phần nào trong số đó vào bất kỳ lúc nào mà không cần thông báo trước. Chúng tôi có thể tùy ý sửa đổi bất kỳ điều khoản nào của Thỏa thuận này bằng cách đăng các điều khoản đã sửa đổi trên trang web Chamm.com. Việc bạn tiếp tục sử dụng Dịch vụ Chamm sau ngày Thỏa thuận sửa đổi có hiệu lực đồng nghĩa với việc bạn chấp nhận các điều khoản. </span></span></span></p>
<p dir="ltr" style="line-height: 1.2; margin-top: 0pt; margin-bottom: 8pt;"><span style="font-size:14px;"><span><span style="color: rgb(0, 0, 0); background-color: transparent; font-weight: 700; font-variant-numeric: normal; font-variant-east-asian: normal; vertical-align: baseline; white-space: pre-wrap;">4. Cuối cùng</span></span></span></p>
<p dir="ltr" style="line-height: 1.2; margin-top: 0pt; margin-bottom: 8pt;"><span style="font-size:14px;"><span id="docs-internal-guid-cfcf0f1b-7fff-0981-4e13-2182d94bfe0a"><span background-color:="" color:="" font-variant-east-asian:="" font-variant-numeric:="" new="" times="" vertical-align:="" white-space:="">Các quyền của bạn theo Thỏa thuận này sẽ tự động chấm dứt mà không cần thông báo nếu bạn không tuân thủ bất kỳ điều khoản nào của nó. Trong trường hợp chấm dứt như vậy, Chamm có thể ngay lập tức thu hồi quyền truy cập của bạn vào Dịch vụ Chamm. Việc Chamm không thể yêu cầu hoặc buộc bạn tuân thủ nghiêm ngặt Thỏa thuận này sẽ không cấu thành sự từ bỏ bất kỳ quyền nào của Chamm.</span></span></span></p>
<p dir="ltr" style="list-style-type: disc; font-size: 12pt; margin-top: 0pt; margin-bottom: 0pt;"><span style="font-size:20px;"><span style="background-color: transparent; font-variant-numeric: normal; font-variant-east-asian: normal; vertical-align: baseline; white-space: pre-wrap;"><span id="docs-internal-guid-cfcf0f1b-7fff-0981-4e13-2182d94bfe0a"><span style="background-color: transparent; font-weight: 700; font-variant-numeric: normal; font-variant-east-asian: normal; vertical-align: baseline; white-space: pre-wrap;">IV. CÁCH LIÊN HỆ VỚI CHAMM KHI CÓ CÂU HỎI</span></span></span></span></p>
<h2 dir="ltr" style="line-height: 1.2; margin-top: 0pt; margin-bottom: 8pt;"><span style="font-size:14px;"><span id="docs-internal-guid-cfcf0f1b-7fff-0981-4e13-2182d94bfe0a"><span background-color:="" color:="" font-variant-east-asian:="" font-variant-numeric:="" new="" times="" vertical-align:="" white-space:=""If you have questions about this policy, you can contact us using the information below:</span></span></span></h2>
<p dir="ltr" style="line-height: 1.2; margin-top: 0pt; margin-bottom: 8pt;"><span style="font-size:14px;"><span id="docs-internal-guid-cfcf0f1b-7fff-0981-4e13-2182d94bfe0a"><span color:="" font-variant-east-asian:="" font-variant-numeric:="" new="" times="" vertical-align:="" white-space:="">Email: </span><a href="mailto:youthmentor.community@gmail.com" style="text-decoration-line: none;">contact@chamm.vn</a></span></span></p>
<p dir="ltr" style="line-height: 1.2; margin-top: 0pt; margin-bottom: 8pt;"><span style="font-size:14px;"><span id="docs-internal-guid-cfcf0f1b-7fff-0981-4e13-2182d94bfe0a"><span color:="" font-variant-east-asian:="" font-variant-numeric:="" new="" times="" vertical-align:="" white-space:="">Hotline: +84 394 531 691</span></span></span></p>`
